steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE_URI}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE_URI}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_IMAGE_URI}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --timeout
      - 3600
      - --set-env-vars
      - GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_LOCATION=global

substitutions:
  _SERVICE_NAME: polyglot-backend
  _REGION: us-central1
  _IMAGE_URI: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/polyglot/polyglot-backend
